logging:
  file:
    name: logs/sboard.log
  level:
    root: info
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
server:
  port: 8080
  servlet:
    context-path: /sboard
spring:
  application:
    name: sboard
    version: ${version}
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: 1234
    url: jdbc:oracle:thin:@//3.36.46.173:1522/XEPDB1 #jdbc:oracle:thin:@localhost:1521:xe
    username: sboard
  devtools:
    livereload:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none #update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: bisunesskyu@gmail.com
    password: detvitlhtcjlqtah
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true



  security:
    user:
      name: user
      password: 1234
      roles: ADMIN

  servlet:
    multipart:
      location: upload
      max-file-size: 10MB